config/routes.rb
Minivest::Application.routes.draw do
  devise_for :users

  resources :trade_leaders
  
  root :to => "welcome#index"

end

app/models/trade_leader.rb
class TradeLeader < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/trade_leaders_controller.rb
class TradeLeadersController < ApplicationController
  # GET /trade_leaders
  # GET /trade_leaders.xml
  def index
    @trade_leaders = TradeLeader.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @trade_leaders }
    end
  end

  # GET /trade_leaders/1
  # GET /trade_leaders/1.xml
  def show
    @trade_leader = TradeLeader.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @trade_leader }
    end
  end

  # GET /trade_leaders/new
  # GET /trade_leaders/new.xml
  def new
    @trade_leader = TradeLeader.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @trade_leader }
    end
  end

  # GET /trade_leaders/1/edit
  def edit
    @trade_leader = TradeLeader.find(params[:id])
  end

  # POST /trade_leaders
  # POST /trade_leaders.xml
  def create
    @trade_leader = TradeLeader.new(params[:trade_leader])

    respond_to do |format|
      if @trade_leader.save
        format.html { redirect_to(@trade_leader, :notice => 'Trade leader was successfully created.') }
        format.xml  { render :xml => @trade_leader, :status => :created, :location => @trade_leader }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @trade_leader.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /trade_leaders/1
  # PUT /trade_leaders/1.xml
  def update
    @trade_leader = TradeLeader.find(params[:id])

    respond_to do |format|
      if @trade_leader.update_attributes(params[:trade_leader])
        format.html { redirect_to(@trade_leader, :notice => 'Trade leader was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @trade_leader.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trade_leaders/1
  # DELETE /trade_leaders/1.xml
  def destroy
    @trade_leader = TradeLeader.find(params[:id])
    @trade_leader.destroy

    respond_to do |format|
      format.html { redirect_to(trade_leaders_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trade_leaders_helper.rb
module TradeLeadersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Minivest</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trade_leaders/_form.html.erb
<%= form_for(@trade_leader) do |f| %>
  <% if @trade_leader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trade_leader.errors.count, "error") %> prohibited this trade_leader from being saved:</h2>

      <ul>
      <% @trade_leader.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trade_leaders/edit.html.erb
<h1>Editing trade_leader</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade_leader %> |
<%= link_to 'Back', trade_leaders_path %>

app/views/trade_leaders/index.html.erb
<h1>Listing trade_leaders</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Bio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trade_leaders.each do |trade_leader| %>
  <tr>
    <td><%= trade_leader.first_name %></td>
    <td><%= trade_leader.last_name %></td>
    <td><%= trade_leader.bio %></td>
    <td><%= link_to 'Show', trade_leader %></td>
    <td><%= link_to 'Edit', edit_trade_leader_path(trade_leader) %></td>
    <td><%= link_to 'Destroy', trade_leader, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trade leader', new_trade_leader_path %>

app/views/trade_leaders/new.html.erb
<h1>New trade_leader</h1>

<%= render 'form' %>

<%= link_to 'Back', trade_leaders_path %>

app/views/trade_leaders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @trade_leader.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @trade_leader.last_name %>
</p>

<p>
  <b>Bio:</b>
  <%= @trade_leader.bio %>
</p>


<%= link_to 'Edit', edit_trade_leader_path(@trade_leader) %> |
<%= link_to 'Back', trade_leaders_path %>